@HTTPS_HostAddress = https://localhost:5001
@HTTP_HOST = http://localhost:5000

### HTTPS weather

GET {{HTTPS_HostAddress}}/weatherforecast/
Accept: application/json

### HTTPS student

GET {{HTTPS_HostAddress}}/student/fullname
Accept: text/plain

### HTTP student

GET {{HTTP_HOST}}/student/fullname
Accept: text/plain

###
